/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joanaklausurabfrager;

import java.awt.Color;

import javax.xml.namespace.QName;

/**
 *
 * @author Cheesy
 */
public class GUI_tester extends javax.swing.JFrame {

    InputOutput io;
    int right;

    /**
     * Creates new form GUI_tester
     */
    public GUI_tester(InputOutput io) {
        initComponents();
        pBackground.setBackground(Color.lightGray);
        this.io = io;
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrOptions = new javax.swing.ButtonGroup();
        pBackground = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        lblFrage = new javax.swing.JLabel();
        rdOp1 = new javax.swing.JRadioButton();
        rdOp2 = new javax.swing.JRadioButton();
        rdOp3 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRichtigFalsch = new javax.swing.JTextPane();
        btPruefenWeiter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFrage.setText("Frage");

        buttonGrOptions.add(rdOp1);
        rdOp1.setText("Option 1");
        rdOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOp1ActionPerformed(evt);
            }
        });

        buttonGrOptions.add(rdOp2);
        rdOp2.setText("Option 2");

        buttonGrOptions.add(rdOp3);
        rdOp3.setText("Option 3");

        txtRichtigFalsch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRichtigFalsch.setEnabled(false);
        jScrollPane1.setViewportView(txtRichtigFalsch);

        btPruefenWeiter.setText("Checken");
        btPruefenWeiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPruefenWeiterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBackgroundLayout = new javax.swing.GroupLayout(pBackground);
        pBackground.setLayout(pBackgroundLayout);
        pBackgroundLayout.setHorizontalGroup(
            pBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addComponent(jSeparator1)
            .addGroup(pBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(btPruefenWeiter))
                    .addGroup(pBackgroundLayout.createSequentialGroup()
                        .addGroup(pBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdOp3)
                            .addComponent(lblFrage)
                            .addComponent(rdOp1)
                            .addComponent(rdOp2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pBackgroundLayout.setVerticalGroup(
            pBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBackgroundLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblFrage)
                .addGap(18, 18, 18)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdOp1)
                .addGap(18, 18, 18)
                .addComponent(rdOp2)
                .addGap(18, 18, 18)
                .addComponent(rdOp3)
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPruefenWeiter))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        rdOp1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOp1ActionPerformed

    private void btPruefenWeiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPruefenWeiterActionPerformed

    	if (btPruefenWeiter.getText().equals("Checken")) {
        	        	
           if(whichSelected() == io.getRight()){
        	   txtRichtigFalsch.setText("RICHTIG!");
        	   pBackground.setBackground(Color.green);
        	        	   
        	   
           }else if(whichSelected() == -1){
        	   return;
           }else{
        	   txtRichtigFalsch.setText("FALSCH!");
        	   pBackground.setBackground(Color.red);
//        	   int fehler = Integer.parseInt(io.frageListe.get(io.qNr)[4])+1;
//        	   String[] temp = io.frageListe.get(io.qNr);
//        	   temp[4] = String.valueOf(fehler);
//        	   io.frageListe.set(io.qNr,temp);
           }

            btPruefenWeiter.setText("Weiter");
        } else {
        	pBackground.setBackground(Color.lightGray);
        	io.qNr = (io.qNr+1) % io.frageListe.size();
        	buttonGrOptions.clearSelection();
        	
        	io.tossQuestion();
        	
        	
        	
            btPruefenWeiter.setText("Checken");
        }

    }//GEN-LAST:event_btPruefenWeiterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               // new GUI_tester().setVisible(true);
//            }
//        });
    }

    public void setQuestion(String q, String a1, String a2, String a3) {
        lblFrage.setText(q);
        rdOp1.setText(a1);
        rdOp2.setText(a2);
        rdOp3.setText(a3);
    }

    public void rightWrong(String s) {
 txtRichtigFalsch.setText(s);
 
    }

    public int whichSelected() {
        if (rdOp1.isSelected()) {
            return 0;
        } else if (rdOp2.isSelected()) {
            return 1;
        } else if (rdOp3.isSelected()) {
            return 2;
        }else{
            return -1;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPruefenWeiter;
    private javax.swing.ButtonGroup buttonGrOptions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFrage;
    private javax.swing.JPanel pBackground;
    private javax.swing.JRadioButton rdOp1;
    private javax.swing.JRadioButton rdOp2;
    private javax.swing.JRadioButton rdOp3;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextPane txtRichtigFalsch;
    // End of variables declaration//GEN-END:variables
}
